language: android
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository
  - extra-google-m2repository
before_script:
- chmod +x gradlew
- cat << "EOF"
-  ('-. .-.               _ (`-.    ('-.  _  .-')   
- ( OO )  /              ( (OO  ) _(  OO)( \( -O )  
- ,--. ,--.  ,--.   ,--._.`     \(,------.,------.  
- |  | |  |   \  `.'  /(__...--'' |  .---'|   /`. ' 
- |   .|  | .-')     /  |  /  | | |  |    |  /  | | 
- |       |(OO  \   /   |  |_.' |(|  '--. |  |_.' | 
- |  .-.  | |   /  /\_  |  .___.' |  .--' |  .  '.' 
- |  | |  | `-./  /.__) |  |      |  `---.|  |\  \  
- `--' `--'   `--'      `--'      `------'`--' '--'
- EOF
script:
- ./gradlew assembleDebug
notifications:
  email: false
