language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_BUILD_TOOLS_VERSION=25.0.1 ANDROID_API_LEVEL=25
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-android-m2repository
  - extra-google-m2repository
  
before_script:
  - chmod +x cute_ghosts
  - chmod +x gradlew

script:
  - ./cute_ghosts
  - ./gradlew assemble

notifications:
  email: false
